{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## The third Lab-assignment (07/22/2022 11:59'AM' - 07/26/2022 11:59PM, 50 points in total)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "The purpose of this exercise is to understand users' information needs, then collect data from different sources for analysis."
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "Question 1 (10 points). Fomulate your domain problem: Describe an interesting research question (or practical question) you have in mind, what kind of data should be collected to answer the question(s)? How many data needed for the analysis? The detail steps for collecting and save the data. "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 22,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "'\\nPlease write you answer here:\\nDue to pandemic the car usage, car prices along with waiting period has been increased drastically. This made people to look\\nfor pre owned cars. The demand for preowned cars is on high. So, the idea is to collect data from a pre owned cars website and \\nperform data analysis, building model and re checking or predicting the car value based on its specifications. \\n\\nFor this analysis we require atleast 1000 - 1500 records(even more). This data is taken by performing web scrapping.\\n\\n'"
      ]
     },
     "execution_count": 22,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "# Your answer here (no code for this question, write down your answer as detail as possible for the above questions):\n",
    "\n",
    "'''\n",
    "Please write you answer here:\n",
    "Due to pandemic the car usage and car prices along with waiting period has been increased drastically. This made people to look\n",
    "for pre owned cars. The demand for preowned cars is on high. So, the idea is to collect data from a pre owned cars website and \n",
    "perform data analysis, building model and re checking or predicting the car value based on its specifications. \n",
    "\n",
    "For this analysis we require atleast 1000 - 1500 records(even more). This data is taken by performing web scrapping.\n",
    "\n",
    "'''"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 23,
   "metadata": {},
   "outputs": [],
   "source": [
    "# You code here (Please add comments in the code):\n",
    "\n",
    "import pandas as pd\n",
    "import requests\n",
    "from bs4 import BeautifulSoup as bs"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 24,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>Name</th>\n",
       "      <th>Mileage</th>\n",
       "      <th>Dealer</th>\n",
       "      <th>Rating</th>\n",
       "      <th>Reviews</th>\n",
       "      <th>Price</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>2022 Mercedes-Benz GLB 250 Base 4MATIC</td>\n",
       "      <td>11,565 mi.</td>\n",
       "      <td>Mercedes-Benz of Stevens Creek</td>\n",
       "      <td>4.7</td>\n",
       "      <td>(1,674 reviews)</td>\n",
       "      <td>$44,980</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>2019 Mercedes-Benz GLS 450 Base 4MATIC</td>\n",
       "      <td>28,655 mi.</td>\n",
       "      <td>Mercedes-Benz of Nanuet</td>\n",
       "      <td>4.9</td>\n",
       "      <td>(242 reviews)</td>\n",
       "      <td>$56,353</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>2022 Mercedes-Benz GLE 350 Base</td>\n",
       "      <td>15,012 mi.</td>\n",
       "      <td>Mercedes-Benz of Tuscaloosa</td>\n",
       "      <td>4.5</td>\n",
       "      <td>(14 reviews)</td>\n",
       "      <td>$70,224</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>2019 Mercedes-Benz GLS 450 4MATIC</td>\n",
       "      <td>29,487 mi.</td>\n",
       "      <td>Mercedes-Benz of Westwood</td>\n",
       "      <td>4.5</td>\n",
       "      <td>(426 reviews)</td>\n",
       "      <td>$55,555</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>2020 Mercedes-Benz GLE 350 Base 4MATIC</td>\n",
       "      <td>52,283 mi.</td>\n",
       "      <td>Mercedes-Benz of South Charlotte</td>\n",
       "      <td>4.8</td>\n",
       "      <td>(1,220 reviews)</td>\n",
       "      <td>$54,724</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>...</th>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1175</th>\n",
       "      <td>2019 Mercedes-Benz GLC 300 Base</td>\n",
       "      <td>29,597 mi.</td>\n",
       "      <td>W.I. Simonson Inc.</td>\n",
       "      <td>4.5</td>\n",
       "      <td>(791 reviews)</td>\n",
       "      <td>$33,999</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1176</th>\n",
       "      <td>2021 Mercedes-Benz AMG GLE 53 Base</td>\n",
       "      <td>7,280 mi.</td>\n",
       "      <td>Mercedes Benz of Hoffman Estates</td>\n",
       "      <td>4.7</td>\n",
       "      <td>(1,114 reviews)</td>\n",
       "      <td>$105,999</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1177</th>\n",
       "      <td>2022 Mercedes-Benz S-Class S 500 4MATIC</td>\n",
       "      <td>2,908 mi.</td>\n",
       "      <td>Mercedes-Benz of Arrowhead</td>\n",
       "      <td>4.5</td>\n",
       "      <td>(232 reviews)</td>\n",
       "      <td>$124,988</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1178</th>\n",
       "      <td>2020 Mercedes-Benz GLE 350 Base 4MATIC</td>\n",
       "      <td>48,825 mi.</td>\n",
       "      <td>Mercedes Benz of Atlantic City</td>\n",
       "      <td>4.6</td>\n",
       "      <td>(1,095 reviews)</td>\n",
       "      <td>$52,574</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1179</th>\n",
       "      <td>2022 Mercedes-Benz GLE 350 Base</td>\n",
       "      <td>4,255 mi.</td>\n",
       "      <td>Mercedes-Benz of Gilbert</td>\n",
       "      <td>4.6</td>\n",
       "      <td>(297 reviews)</td>\n",
       "      <td>$56,888</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "<p>1180 rows × 6 columns</p>\n",
       "</div>"
      ],
      "text/plain": [
       "                                         Name     Mileage  \\\n",
       "0      2022 Mercedes-Benz GLB 250 Base 4MATIC  11,565 mi.   \n",
       "1      2019 Mercedes-Benz GLS 450 Base 4MATIC  28,655 mi.   \n",
       "2             2022 Mercedes-Benz GLE 350 Base  15,012 mi.   \n",
       "3           2019 Mercedes-Benz GLS 450 4MATIC  29,487 mi.   \n",
       "4      2020 Mercedes-Benz GLE 350 Base 4MATIC  52,283 mi.   \n",
       "...                                       ...         ...   \n",
       "1175          2019 Mercedes-Benz GLC 300 Base  29,597 mi.   \n",
       "1176       2021 Mercedes-Benz AMG GLE 53 Base   7,280 mi.   \n",
       "1177  2022 Mercedes-Benz S-Class S 500 4MATIC   2,908 mi.   \n",
       "1178   2020 Mercedes-Benz GLE 350 Base 4MATIC  48,825 mi.   \n",
       "1179          2022 Mercedes-Benz GLE 350 Base   4,255 mi.   \n",
       "\n",
       "                                Dealer Rating          Reviews     Price  \n",
       "0       Mercedes-Benz of Stevens Creek    4.7  (1,674 reviews)   $44,980  \n",
       "1              Mercedes-Benz of Nanuet    4.9    (242 reviews)   $56,353  \n",
       "2          Mercedes-Benz of Tuscaloosa    4.5     (14 reviews)   $70,224  \n",
       "3            Mercedes-Benz of Westwood    4.5    (426 reviews)   $55,555  \n",
       "4     Mercedes-Benz of South Charlotte    4.8  (1,220 reviews)   $54,724  \n",
       "...                                ...    ...              ...       ...  \n",
       "1175                W.I. Simonson Inc.    4.5    (791 reviews)   $33,999  \n",
       "1176  Mercedes Benz of Hoffman Estates    4.7  (1,114 reviews)  $105,999  \n",
       "1177        Mercedes-Benz of Arrowhead    4.5    (232 reviews)  $124,988  \n",
       "1178    Mercedes Benz of Atlantic City    4.6  (1,095 reviews)   $52,574  \n",
       "1179          Mercedes-Benz of Gilbert    4.6    (297 reviews)   $56,888  \n",
       "\n",
       "[1180 rows x 6 columns]"
      ]
     },
     "execution_count": 24,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "name = []\n",
    "dealer = []\n",
    "mileage = []\n",
    "rating = []\n",
    "reviews = []\n",
    "price = []\n",
    "\n",
    "for i in range (1,60):\n",
    "    \n",
    "    \n",
    "    website = 'https://www.cars.com/shopping/results/?page='+ str(i) +'&page_size=20&dealer_id=&list_price_max=&list_price_min=&makes[]=mercedes_benz&maximum_distance=20&mileage_max=&sort=best_match_desc&stock_type=cpo&year_max=&year_min=&zip=' \n",
    "    \n",
    "    response = requests.get(website)\n",
    "    \n",
    "    soup = BeautifulSoup(response.content, 'html.parser')\n",
    "    \n",
    "    data = soup.find_all('div', {'class' : 'vehicle-card'})\n",
    "    \n",
    "    for i in data:\n",
    "\n",
    "        name.append(i.find('h2').get_text()) \n",
    "        dealer.append(i.find('div', {'class':'dealer-name'}).get_text().strip())\n",
    "        mileage.append(i.find('div', {'class':'mileage'}).get_text())\n",
    "        rating.append(i.find('span', {'class':'sds-rating__count'}).get_text())\n",
    "        reviews.append(i.find('span', {'class':'sds-rating__link'}).get_text())\n",
    "        price.append(i.find('span', {'class':'primary-price'}).get_text())\n",
    "df = pd.DataFrame({'Name': name, 'Mileage':mileage, 'Dealer':dealer,\n",
    "                                'Rating': rating, 'Reviews': reviews, 'Price': price})\n",
    "df\n",
    "\n"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "Question 3 (10 points). Understand the data quality: Search a second hand dataset (any dataset) from kaggle or other websites. Describe the data quality problem of the dataset and explain your strtegy to clean the data."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 25,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "'\\nHere a dataset on ranking from kaggle is considered.\\nThe stratagy followed to clean data is\\n\\nimported data from csv\\ndrop unwanted columns(index is not required)\\nsyllabus column has only two options(NEW and NA). so, the column is dropped because it shows no effect.\\nChecked for na values and found some na values. Then the NA records with NA are dropped.\\nSome of the records contain \"-\". The record with \"-\" are replaced with 0.\\nsterem cannot be 0. so, 0 in stream is encoded as others.\\nThen encode of categorical variables is performed. This converts categorical variable to numerical. Drop frst is used to drop one of the \\nfeature in predictors.\\nNow the data is fully cleand and converted to numerical representation.\\n\\n\\n'"
      ]
     },
     "execution_count": 25,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "# Your answer here (no code for this question, write down your answer as detail as possible for the above questions):\n",
    "'''\n",
    "Here a dataset on ranking from kaggle is considered.\n",
    "The stratagy followed to clean data is\n",
    "\n",
    "imported data from csv\n",
    "drop unwanted columns(index is not required)\n",
    "Ckeck for NULL values using isnull() function\n",
    "syllabus column has only two options(NEW and NA). so, the column is dropped because it shows no effect.\n",
    "Checked for na values and found some na values. Then the NA records with NA are dropped.\n",
    "Some of the records contain \"-\". The record with \"-\" are replaced with 0.\n",
    "sterem cannot be 0. so, 0 in stream is encoded as others.\n",
    "Then encode of categorical variables is performed. This converts categorical variable to numerical. Drop frst is used to drop one of the \n",
    "feature in predictors.\n",
    "We perform visualization to analyze the data. this consist of univarient and bivarient anaysis.\n",
    "Now the data is fully cleand and converted to numerical representation.\n",
    "\n",
    "Modeling is performed based on target variable\n",
    "\n",
    "'''"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 26,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "C:\\Users\\Bharath\\anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py:3444: DtypeWarning: Columns (11) have mixed types.Specify dtype option on import or set low_memory=False.\n",
      "  exec(code_obj, self.user_global_ns, self.user_ns)\n"
     ]
    },
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>index</th>\n",
       "      <th>stream</th>\n",
       "      <th>Zscore</th>\n",
       "      <th>sub1_r</th>\n",
       "      <th>sub2_r</th>\n",
       "      <th>sub3_r</th>\n",
       "      <th>cgt_r</th>\n",
       "      <th>general_english_r</th>\n",
       "      <th>birth_day</th>\n",
       "      <th>birth_month</th>\n",
       "      <th>birth_year</th>\n",
       "      <th>gender</th>\n",
       "      <th>island_rank</th>\n",
       "      <th>district_rank</th>\n",
       "      <th>syllabus</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>0</td>\n",
       "      <td>ARTS</td>\n",
       "      <td>-0.355</td>\n",
       "      <td>S</td>\n",
       "      <td>C</td>\n",
       "      <td>S</td>\n",
       "      <td>56</td>\n",
       "      <td>S</td>\n",
       "      <td>31</td>\n",
       "      <td>May</td>\n",
       "      <td>2001</td>\n",
       "      <td>0</td>\n",
       "      <td>64994</td>\n",
       "      <td>4336</td>\n",
       "      <td>(NEW)</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>1</td>\n",
       "      <td>ARTS</td>\n",
       "      <td>-0.2648</td>\n",
       "      <td>S</td>\n",
       "      <td>C</td>\n",
       "      <td>C</td>\n",
       "      <td>32</td>\n",
       "      <td>C</td>\n",
       "      <td>13</td>\n",
       "      <td>January</td>\n",
       "      <td>2002</td>\n",
       "      <td>0</td>\n",
       "      <td>62338</td>\n",
       "      <td>4154</td>\n",
       "      <td>(NEW)</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>2</td>\n",
       "      <td>COMMERCE</td>\n",
       "      <td>-0.476</td>\n",
       "      <td>S</td>\n",
       "      <td>S</td>\n",
       "      <td>S</td>\n",
       "      <td>50</td>\n",
       "      <td>S</td>\n",
       "      <td>16</td>\n",
       "      <td>August</td>\n",
       "      <td>2001</td>\n",
       "      <td>0</td>\n",
       "      <td>37307</td>\n",
       "      <td>6910</td>\n",
       "      <td>(NEW)</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>3</td>\n",
       "      <td>COMMERCE</td>\n",
       "      <td>-0.1012</td>\n",
       "      <td>C</td>\n",
       "      <td>C</td>\n",
       "      <td>S</td>\n",
       "      <td>34</td>\n",
       "      <td>S</td>\n",
       "      <td>16</td>\n",
       "      <td>August</td>\n",
       "      <td>2001</td>\n",
       "      <td>0</td>\n",
       "      <td>30449</td>\n",
       "      <td>5678</td>\n",
       "      <td>(NEW)</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>4</td>\n",
       "      <td>COMMERCE</td>\n",
       "      <td>0.6014</td>\n",
       "      <td>C</td>\n",
       "      <td>C</td>\n",
       "      <td>B</td>\n",
       "      <td>36</td>\n",
       "      <td>S</td>\n",
       "      <td>7</td>\n",
       "      <td>August</td>\n",
       "      <td>2000</td>\n",
       "      <td>0</td>\n",
       "      <td>17010</td>\n",
       "      <td>3269</td>\n",
       "      <td>(NEW)</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>...</th>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>306206</th>\n",
       "      <td>306206</td>\n",
       "      <td>ARTS</td>\n",
       "      <td>-0.1201</td>\n",
       "      <td>C</td>\n",
       "      <td>C</td>\n",
       "      <td>S</td>\n",
       "      <td>26</td>\n",
       "      <td>B</td>\n",
       "      <td>Invalid error</td>\n",
       "      <td>NaN</td>\n",
       "      <td>Invalid error</td>\n",
       "      <td>0</td>\n",
       "      <td>57522</td>\n",
       "      <td>4442</td>\n",
       "      <td>(NEW)</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>306207</th>\n",
       "      <td>306207</td>\n",
       "      <td>-</td>\n",
       "      <td>-0.8013</td>\n",
       "      <td>F</td>\n",
       "      <td>S</td>\n",
       "      <td>S</td>\n",
       "      <td>30</td>\n",
       "      <td>S</td>\n",
       "      <td>Invalid error</td>\n",
       "      <td>NaN</td>\n",
       "      <td>Invalid error</td>\n",
       "      <td>0</td>\n",
       "      <td>-</td>\n",
       "      <td>-</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>306208</th>\n",
       "      <td>306208</td>\n",
       "      <td>-</td>\n",
       "      <td>-0.6166</td>\n",
       "      <td>S</td>\n",
       "      <td>F</td>\n",
       "      <td>C</td>\n",
       "      <td>18</td>\n",
       "      <td>Absent</td>\n",
       "      <td>Invalid error</td>\n",
       "      <td>NaN</td>\n",
       "      <td>Invalid error</td>\n",
       "      <td>0</td>\n",
       "      <td>-</td>\n",
       "      <td>-</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>306209</th>\n",
       "      <td>306209</td>\n",
       "      <td>-</td>\n",
       "      <td>-0.9112</td>\n",
       "      <td>F</td>\n",
       "      <td>S</td>\n",
       "      <td>S</td>\n",
       "      <td>Absent</td>\n",
       "      <td>F</td>\n",
       "      <td>Invalid error</td>\n",
       "      <td>NaN</td>\n",
       "      <td>Invalid error</td>\n",
       "      <td>0</td>\n",
       "      <td>-</td>\n",
       "      <td>-</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>306210</th>\n",
       "      <td>306210</td>\n",
       "      <td>-</td>\n",
       "      <td>-0.9845</td>\n",
       "      <td>S</td>\n",
       "      <td>S</td>\n",
       "      <td>F</td>\n",
       "      <td>30</td>\n",
       "      <td>Absent</td>\n",
       "      <td>Invalid error</td>\n",
       "      <td>NaN</td>\n",
       "      <td>Invalid error</td>\n",
       "      <td>0</td>\n",
       "      <td>-</td>\n",
       "      <td>-</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "<p>306211 rows × 15 columns</p>\n",
       "</div>"
      ],
      "text/plain": [
       "         index    stream   Zscore sub1_r sub2_r sub3_r   cgt_r  \\\n",
       "0            0      ARTS   -0.355      S      C      S      56   \n",
       "1            1      ARTS  -0.2648      S      C      C      32   \n",
       "2            2  COMMERCE   -0.476      S      S      S      50   \n",
       "3            3  COMMERCE  -0.1012      C      C      S      34   \n",
       "4            4  COMMERCE   0.6014      C      C      B      36   \n",
       "...        ...       ...      ...    ...    ...    ...     ...   \n",
       "306206  306206      ARTS  -0.1201      C      C      S      26   \n",
       "306207  306207         -  -0.8013      F      S      S      30   \n",
       "306208  306208         -  -0.6166      S      F      C      18   \n",
       "306209  306209         -  -0.9112      F      S      S  Absent   \n",
       "306210  306210         -  -0.9845      S      S      F      30   \n",
       "\n",
       "       general_english_r      birth_day birth_month     birth_year gender  \\\n",
       "0                      S             31         May           2001      0   \n",
       "1                      C             13     January           2002      0   \n",
       "2                      S             16      August           2001      0   \n",
       "3                      S             16      August           2001      0   \n",
       "4                      S              7      August           2000      0   \n",
       "...                  ...            ...         ...            ...    ...   \n",
       "306206                 B  Invalid error         NaN  Invalid error      0   \n",
       "306207                 S  Invalid error         NaN  Invalid error      0   \n",
       "306208            Absent  Invalid error         NaN  Invalid error      0   \n",
       "306209                 F  Invalid error         NaN  Invalid error      0   \n",
       "306210            Absent  Invalid error         NaN  Invalid error      0   \n",
       "\n",
       "       island_rank district_rank syllabus  \n",
       "0            64994          4336    (NEW)  \n",
       "1            62338          4154    (NEW)  \n",
       "2            37307          6910    (NEW)  \n",
       "3            30449          5678    (NEW)  \n",
       "4            17010          3269    (NEW)  \n",
       "...            ...           ...      ...  \n",
       "306206       57522          4442    (NEW)  \n",
       "306207           -             -      NaN  \n",
       "306208           -             -      NaN  \n",
       "306209           -             -      NaN  \n",
       "306210           -             -      NaN  \n",
       "\n",
       "[306211 rows x 15 columns]"
      ]
     },
     "execution_count": 26,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "import pandas as pd\n",
    "df1 = pd.read_csv('al_results_2020.csv')\n",
    "df1\n",
    "df1=df1.drop(['index'],axis=1)\n",
    "df1\n",
    "df1['syllabus'].unique()\n",
    "df1=df1.drop(['syllabus'],axis=1)\n",
    "df1\n",
    "df1.isna().sum()\n",
    "df1.dropna(inplace=True)\n",
    "df1\n",
    "df1.isna().sum()\n",
    "df1=df1.replace(\"-\",0)\n",
    "df1.isnull().sum()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 35,
   "metadata": {},
   "outputs": [],
   "source": [
    "import statistics\n",
    "df1['stream']=df1['stream'].replace(0,'others')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 36,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "array(['64994', '62338', '37307', ..., '20662', '55775', '7741'],\n",
       "      dtype=object)"
      ]
     },
     "execution_count": 36,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "df1['island_rank'].unique()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 37,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>stream</th>\n",
       "      <th>Zscore</th>\n",
       "      <th>sub1_r</th>\n",
       "      <th>sub2_r</th>\n",
       "      <th>sub3_r</th>\n",
       "      <th>cgt_r</th>\n",
       "      <th>general_english_r</th>\n",
       "      <th>birth_day</th>\n",
       "      <th>birth_month</th>\n",
       "      <th>birth_year</th>\n",
       "      <th>gender</th>\n",
       "      <th>island_rank</th>\n",
       "      <th>district_rank</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>ARTS</td>\n",
       "      <td>-0.355</td>\n",
       "      <td>S</td>\n",
       "      <td>C</td>\n",
       "      <td>S</td>\n",
       "      <td>56</td>\n",
       "      <td>S</td>\n",
       "      <td>31</td>\n",
       "      <td>May</td>\n",
       "      <td>2001</td>\n",
       "      <td>0</td>\n",
       "      <td>64994</td>\n",
       "      <td>4336</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>ARTS</td>\n",
       "      <td>-0.2648</td>\n",
       "      <td>S</td>\n",
       "      <td>C</td>\n",
       "      <td>C</td>\n",
       "      <td>32</td>\n",
       "      <td>C</td>\n",
       "      <td>13</td>\n",
       "      <td>January</td>\n",
       "      <td>2002</td>\n",
       "      <td>0</td>\n",
       "      <td>62338</td>\n",
       "      <td>4154</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>COMMERCE</td>\n",
       "      <td>-0.476</td>\n",
       "      <td>S</td>\n",
       "      <td>S</td>\n",
       "      <td>S</td>\n",
       "      <td>50</td>\n",
       "      <td>S</td>\n",
       "      <td>16</td>\n",
       "      <td>August</td>\n",
       "      <td>2001</td>\n",
       "      <td>0</td>\n",
       "      <td>37307</td>\n",
       "      <td>6910</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>COMMERCE</td>\n",
       "      <td>-0.1012</td>\n",
       "      <td>C</td>\n",
       "      <td>C</td>\n",
       "      <td>S</td>\n",
       "      <td>34</td>\n",
       "      <td>S</td>\n",
       "      <td>16</td>\n",
       "      <td>August</td>\n",
       "      <td>2001</td>\n",
       "      <td>0</td>\n",
       "      <td>30449</td>\n",
       "      <td>5678</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>COMMERCE</td>\n",
       "      <td>0.6014</td>\n",
       "      <td>C</td>\n",
       "      <td>C</td>\n",
       "      <td>B</td>\n",
       "      <td>36</td>\n",
       "      <td>S</td>\n",
       "      <td>7</td>\n",
       "      <td>August</td>\n",
       "      <td>2000</td>\n",
       "      <td>0</td>\n",
       "      <td>17010</td>\n",
       "      <td>3269</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>...</th>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>306185</th>\n",
       "      <td>others</td>\n",
       "      <td>-0.6375</td>\n",
       "      <td>S</td>\n",
       "      <td>S</td>\n",
       "      <td>F</td>\n",
       "      <td>50</td>\n",
       "      <td>B</td>\n",
       "      <td>8</td>\n",
       "      <td>January</td>\n",
       "      <td>1995</td>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>306186</th>\n",
       "      <td>ENGINEERING TECHNOLOGY</td>\n",
       "      <td>0.1325</td>\n",
       "      <td>S</td>\n",
       "      <td>S</td>\n",
       "      <td>C</td>\n",
       "      <td>Absent</td>\n",
       "      <td>Absent</td>\n",
       "      <td>2</td>\n",
       "      <td>January</td>\n",
       "      <td>1999</td>\n",
       "      <td>1</td>\n",
       "      <td>7741</td>\n",
       "      <td>466</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>306192</th>\n",
       "      <td>ARTS</td>\n",
       "      <td>-0.2914</td>\n",
       "      <td>C</td>\n",
       "      <td>S</td>\n",
       "      <td>S</td>\n",
       "      <td>26</td>\n",
       "      <td>F</td>\n",
       "      <td>0</td>\n",
       "      <td>January</td>\n",
       "      <td>1999</td>\n",
       "      <td>1</td>\n",
       "      <td>63193</td>\n",
       "      <td>2873</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>306197</th>\n",
       "      <td>ARTS</td>\n",
       "      <td>-0.1452</td>\n",
       "      <td>S</td>\n",
       "      <td>C</td>\n",
       "      <td>C</td>\n",
       "      <td>30</td>\n",
       "      <td>C</td>\n",
       "      <td>5</td>\n",
       "      <td>January</td>\n",
       "      <td>1999</td>\n",
       "      <td>1</td>\n",
       "      <td>58376</td>\n",
       "      <td>1996</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>306199</th>\n",
       "      <td>others</td>\n",
       "      <td>0</td>\n",
       "      <td>F</td>\n",
       "      <td>F</td>\n",
       "      <td>S</td>\n",
       "      <td>Absent</td>\n",
       "      <td>Absent</td>\n",
       "      <td>7</td>\n",
       "      <td>January</td>\n",
       "      <td>1999</td>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "<p>305469 rows × 13 columns</p>\n",
       "</div>"
      ],
      "text/plain": [
       "                        stream   Zscore sub1_r sub2_r sub3_r   cgt_r  \\\n",
       "0                         ARTS   -0.355      S      C      S      56   \n",
       "1                         ARTS  -0.2648      S      C      C      32   \n",
       "2                     COMMERCE   -0.476      S      S      S      50   \n",
       "3                     COMMERCE  -0.1012      C      C      S      34   \n",
       "4                     COMMERCE   0.6014      C      C      B      36   \n",
       "...                        ...      ...    ...    ...    ...     ...   \n",
       "306185                  others  -0.6375      S      S      F      50   \n",
       "306186  ENGINEERING TECHNOLOGY   0.1325      S      S      C  Absent   \n",
       "306192                    ARTS  -0.2914      C      S      S      26   \n",
       "306197                    ARTS  -0.1452      S      C      C      30   \n",
       "306199                  others        0      F      F      S  Absent   \n",
       "\n",
       "       general_english_r birth_day birth_month birth_year gender island_rank  \\\n",
       "0                      S        31         May       2001      0       64994   \n",
       "1                      C        13     January       2002      0       62338   \n",
       "2                      S        16      August       2001      0       37307   \n",
       "3                      S        16      August       2001      0       30449   \n",
       "4                      S         7      August       2000      0       17010   \n",
       "...                  ...       ...         ...        ...    ...         ...   \n",
       "306185                 B         8     January       1995      1           0   \n",
       "306186            Absent         2     January       1999      1        7741   \n",
       "306192                 F         0     January       1999      1       63193   \n",
       "306197                 C         5     January       1999      1       58376   \n",
       "306199            Absent         7     January       1999      1           0   \n",
       "\n",
       "       district_rank  \n",
       "0               4336  \n",
       "1               4154  \n",
       "2               6910  \n",
       "3               5678  \n",
       "4               3269  \n",
       "...              ...  \n",
       "306185             0  \n",
       "306186           466  \n",
       "306192          2873  \n",
       "306197          1996  \n",
       "306199             0  \n",
       "\n",
       "[305469 rows x 13 columns]"
      ]
     },
     "execution_count": 37,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "df1\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "pd.get_dummies(df1,drop_first=True)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.7"
  },
  "vscode": {
   "interpreter": {
    "hash": "5c6a7f839effdddf35473dacbb9a8184e57ebbba5133cab03b12e4f28d4f0d0f"
   }
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
